### ISSUE TITLE
关于撰写文档时的一些问题

### ISSUE THREAD

**Issue by SunnyHaze** [scu-covariant/scu-PM#1]
1. cov是否能够实现"日历点选"功能？
这个功能感觉有些棘手，之前也没有见过。
2. 确实还是不太会使`cspkg`，对于新手教学需要完善这部分，折腾一晚上还是没跑起来`darwin库`，教学内容对应开发文档中的`/doc/HowToCov.md`文件，希望老李有功夫可以稍微科普一下，辛苦，感谢。

**Comment by mikecovlee** [comment]
这都肯定可以实现的，不是太难的事情。你可以看一下example里db_editor.csc的实现细节
